### ISSUE TITLE
capabilities mismatches

### ISSUE THREAD

**Issue by notroj** [rpminspect/rpminspect-data-fedora#30]
httpd capabilities are not matching against the Fedora data (at least for Fedora 38 CI, I haven't checked earlier releases).

`/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml --workdir /var/ARTIFACTS/work-rpminspectt7i39a64/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspectt7i39a64/rpminspect/execute/data/rpminspect/data/result.json --verbose --release=fc38 --profile=rawhide httpd-2.4.54-9.fc38 95558946`

is giving the error:

```
File capabilities for /usr/sbin/suexec (cap_setgid,cap_setuid=ep) not found on the capabilities list on x86_64
```

For this issue in RHEL9 IIRC we did `s/=/+/` in the capability strings to make things work again?

**Comment by dcantrell** [comment]
Yeah, if the output has changed then these files will need to be updated.  Go ahead and make the changes and send a PR and I can merge it.
