### ISSUE TITLE
Missing product configuration for Fedora 40

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect-data-fedora#42]
I have two issues when using rpminspect-data-fedora on Fedora 40:

* There <https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/> is no fedora-40-x86_64 directory, hence installation from <https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/fedora-$releasever-$arch/> YUM repository fails.

* After manually installing fedora-rawhide build <https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/fedora-rawhide-x86_64/06274029-rpminspect-data-fedora/rpminspect-data-fedora-1.11-0.1.202308141417git9c3e5fb.fc40.noarch.rpm>, I get this error:

~~~~
$ rpminspect -c /usr/share/rpminspect/fedora.yaml ../RPMS/x86_64/openvpn-otp-1.0^20230731git47f8ccf-1.fc40.x86_64.rpm 
rpminspect: *** unable to determine product release or none specified (-r).
~~~~

I guess it's because fedora.yaml is missing a pattern for fc40 product.

**Comment by dcantrell** [comment]
Fedora 40 rules added.  The Copr repo for F40 will appear at some point and I have things set up to automatically pick up new releases when they are created.
