### ISSUE TITLE
javabytecode: missing setting for fc34

### ISSUE THREAD

**Issue by decathorpe** [rpminspect/rpminspect-data-fedora#9]
https://github.com/rpminspect/rpminspect-data-fedora/blob/master/fedora.yaml#L378

This is missing a setting for fedora 34 / rawhide, which should also be 55, same as fc33.

The default fallback value is also a tad low :)

**Comment by dcantrell** [comment]
Added it to fedora.yaml.

This data package is meant to be collectively maintained by all developers, so feel free to send a PR for this type of change in the future.
